services:
  hlatyping-env:
    image: gnasello/hlatyping-env:2025-01-24
    container_name: hlatyping-env
    ports:
      - 8888:8888
    #volumes:
    #  - /local/path:/home/jovyan/researcher_home
    environment:
    - GRANT_SUDO=yes
    user: root
