services:
  hlatyping-env:
    image: gnasello/hlatyping-env:2025-01-24
    container_name: hlatyping-env
    ports:
      - 8888:8888
    #volumes:
    #  - /local/path:/home/jovyan/researcher_home
    environment:
    #  - NB_UID=1000
    #  - NB_GID=100
    #  - CHOWN_HOME=yes
    #  - CHOWN_HOME_OPTS=-R
      - GRANT_SUDO=yes
    user: root
